{{- if .Values.mapstorage.env.ENABLE_BASIC_AUTHENTICATION }}
{{- $name := .Values.mapstorage.env.AUTHENTICATION_USER | required ".Values.mapstorage.env.AUTHENTICATION_USER is required when .Values.mapstorage.env.ENABLE_BASIC_AUTHENTICATION is set" }}
{{- $password := .Values.mapstorage.secretEnv.AUTHENTICATION_PASSWORD | required ".Values.mapstorage.secretEnv.AUTHENTICATION_PASSWORD is required when .Values.mapstorage.env.ENABLE_BASIC_AUTHENTICATION is set" }}
{{- end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-secret-env-mapstorage
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.commonSecretEnv }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}

  {{- range $key, $val := .Values.mapstorage.secretEnv }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
