plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs

nodeLinker: pnpm


packageExtensions:
  # This is required for vitest as it accesses jsdom through local-pkg on its behalf
  # See also: https://github.com/vitest-dev/vitest/issues/899#issuecomment-1084791846
  # and: https://github.com/antfu/local-pkg/issues/2
  "local-pkg@*":
    dependencies:
      "jsdom": "*"
