version: "3"
services:
  testcafe:
    build: tests/
    working_dir: /project/tests
    # Run as root to have the right to access /var/run/docker.sock
    user: root
    environment:
      BROWSER: "chromium --use-fake-device-for-media-stream"
    volumes:
      - ./:/project
      - ./maps:/maps
      - /var/run/docker.sock:/var/run/docker.sock
  #  security_opt:
  #    - seccomp:unconfined
