version: "3.6"
services:
  # overrides for e2e tests to be closer to production
  # use with command:
  # docker-compose -f docker-compose.yaml -f docker-compose.e2e.yml up -d --build

  front:
    image: thecodingmachine/workadventure-front:${DOCKER_TAG:-develop}
    build:
      context: ./
      dockerfile: front/Dockerfile
      cache_from:
        - thecodingmachine/workadventure-front:${DOCKER_TAG:-develop}
      args:
        BUILDKIT_INLINE_CACHE: 1
    command: /start_nginx.sh
    volumes: []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`play.workadventure.localhost`)"
      - "traefik.http.routers.front.entryPoints=web"
      - "traefik.http.services.front.loadbalancer.server.port=80"

  chat:
    image: thecodingmachine/workadventure-chat:${DOCKER_TAG:-develop}
    build:
      context: ./
      dockerfile: front/chat/Dockerfile
      cache_from:
        - thecodingmachine/workadventure-chat:${DOCKER_TAG:-develop}
      args:
        BUILDKIT_INLINE_CACHE: 1
    command: /start_nginx.sh
    volumes: []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=Host(`chat.workadventure.localhost`)"
      - "traefik.http.routers.chat.entryPoints=web"
      - "traefik.http.services.chat.loadbalancer.server.port=80"

  pusher:
    image: thecodingmachine/workadventure-pusher:${DOCKER_TAG:-develop}
    build:
      context: ./
      dockerfile: pusher/Dockerfile
      cache_from:
        - thecodingmachine/workadventure-pusher:${DOCKER_TAG:-develop}
      args:
        BUILDKIT_INLINE_CACHE: 1
    command: yarn run runprod
    volumes: []
    environment:
      ENABLE_OPENAPI_ENDPOINT: "false"

  back:
    image: thecodingmachine/workadventure-back:${DOCKER_TAG:-develop}
    build:
      context: ./
      dockerfile: back/Dockerfile
      cache_from:
        - thecodingmachine/workadventure-back:${DOCKER_TAG:-develop}
      args:
        BUILDKIT_INLINE_CACHE: 1
    command: yarn run runprod
    volumes: []

  map-storage:
    image: thecodingmachine/workadventure-map-storage:${DOCKER_TAG:-develop}
    build:
      context: ./
      dockerfile: map-storage/Dockerfile
      cache_from:
        - thecodingmachine/workadventure-map-storage:${DOCKER_TAG:-develop}
      args:
        BUILDKIT_INLINE_CACHE: 1
    command: yarn run start:prod
    volumes: []


  uploader:
    image: thecodingmachine/workadventure-uploader:${DOCKER_TAG:-develop}
    build:
      context: ./
      dockerfile: uploader/Dockerfile
      cache_from:
        - thecodingmachine/workadventure-uploader:${DOCKER_TAG:-develop}
      args:
        BUILDKIT_INLINE_CACHE: 1
    command: yarn run runprod
    volumes: []

  ejabberd:
    image: thecodingmachine/workadventure-simple-ecs:${DOCKER_TAG:-develop}
    build:
      context: xmpp/
      cache_from:
        - thecodingmachine/workadventure-simple-ecs:${DOCKER_TAG:-develop}
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes: []
