{{- if .Values.maps.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-env-maps
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
data:
  FRONT_URL: {{ include "workadventure.playUrl" . | quote }}

  {{- range $key, $val := .Values.commonEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  {{- range $key, $val := .Values.maps.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
