{{- if include "workadventure.isBooleanText" .Values.mapstorage.env.ENABLE_BASIC_AUTHENTICATION }}
{{- $name := .Values.mapstorage.env.AUTHENTICATION_USER | required ".Values.mapstorage.env.AUTHENTICATION_USER is required when .Values.mapstorage.env.ENABLE_BASIC_AUTHENTICATION is set" }}
{{- $password := .Values.mapstorage.secretEnv.AUTHENTICATION_PASSWORD | required ".Values.mapstorage.secretEnv.AUTHENTICATION_PASSWORD is required when .Values.mapstorage.env.ENABLE_BASIC_AUTHENTICATION is set" }}
{{- end }}

{{- $bearerAuthentication := "" }}
{{- if and .Values.mapstorage.env.ENABLE_BEARER_AUTHENTICATION (not .Values.mapstorage.secretEnv.AUTHENTICATION_TOKEN) }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secret-env-mapstorage" (include "workadventure.fullname" .))) }}

  {{- $bearerAuthentication = (randAlpha 32) | b64enc }}

  {{- if $secret }}
  {{- $bearerAuthentication = coalesce (index $secret.data "AUTHENTICATION_TOKEN") $bearerAuthentication }}
  {{- end }}
{{- end }}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-secret-env-mapstorage
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $bearerAuthentication }}
  AUTHENTICATION_TOKEN: {{ $bearerAuthentication | quote }}
  {{- end }}

  {{- range $key, $val := .Values.commonSecretEnv }}
  {{ $key }}: {{ $val | default "" | b64enc | quote }}
  {{- end }}

  {{- range $key, $val := .Values.mapstorage.secretEnv }}
  {{ $key }}: {{ $val | default "" | b64enc | quote }}
  {{- end }}
