{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secret-env-shared" (include "workadventure.fullname" .))) }}

{{- $secretKey := (randAlpha 32) | b64enc }}
{{- if $secret }}
{{- $secretKey = index $secret.data "SECRET_KEY" }}
{{- end -}}

{{- $ejabberdJwtSecret := (randAlpha 32) | b64enc }}
{{- if $secret }}
{{- $ejabberdJwtSecret = index $secret.data "EJABBERD_JWT_SECRET" }}
{{- end -}}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-secret-env-shared
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secretKey | b64enc | default $secretKey | quote }}
  EJABBERD_JWT_SECRET: {{ .Values.ejabberdJwtSecret | b64enc | default $ejabberdJwtSecret | quote }}
