name: Cleanup images and environments

on:
  - delete

# Enables BuildKit
env:
  DOCKER_BUILDKIT: 1

jobs:

  delete_namespace:
    runs-on: ubuntu-latest

    steps:
      # Create a slugified value of the branch
      - uses: rlespinasse/github-slug-action@1.1.0

      - name: Cleanup
        uses: docker://thecodingmachine/deeployer-cleanup-action@master
        env:
          KUBE_CONFIG_FILE: ${{ secrets.KUBE_CONFIG_FILE }}
        with:
          namespace: workadventure-${{ env.GITHUB_REF_SLUG }}
