name: 'End to end tests'

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: tests
      - name: Install Playwright
        run: npx playwright install --with-deps
        working-directory: tests
      - name: 'Setup .env file'
        run: cp .env.template .env
      - name: Build WorkAdventure
        run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.yaml -f docker-compose.e2e.yml build --parallel
      - name: Start WorkAdventure
        run: docker-compose -f docker-compose.yaml -f docker-compose-oidc.yaml -f docker-compose.e2e.yml up -d
      - name: Wait for environment to Start
        run: sleep 60
      - name: Run Playwright tests
        run: npm run test-prod-like -- tests/chat.spec.ts
        working-directory: tests
      - name: Display docker-compose logs on failure
        run: docker-compose -f docker-compose.yaml -f docker-compose-oidc.yaml -f docker-compose.e2e.yml logs
        if: failure()
      - name: Display containers state
        run: docker-compose -f docker-compose.yaml -f docker-compose-oidc.yaml -f docker-compose.e2e.yml ps
        if: failure()
      - name: Side-load docker-compose logs in the playwright report
        run: docker-compose -f docker-compose.yaml -f docker-compose-oidc.yaml -f docker-compose.e2e.yml logs > tests/playwright-report/docker-compose.log
        if: failure()
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 30
