name: 'End to end tests'

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
        working-directory: tests
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: 'Setup .env file'
        run: cp .env.template .env
      - name: Install messages dependencies
        run: yarn install
        working-directory: messages
      - name: Build proto messages
        run: yarn run proto-all
        working-directory: messages
      - name: Build WorkAdventure
        run: docker-compose -f docker-compose.yaml -f docker-compose.e2e.yml build --parallel
      - name: Start WorkAdventure
        run: docker-compose -f docker-compose.yaml -f docker-compose.e2e.yml up -d
      - name: Wait for environment to Start
        run: sleep 60
      - name: Run Playwright tests
        run: npm run test-prod-like
        working-directory: tests
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 30
