name: 'End to end tests'

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: tests
      - name: Install Playwright
        run: npx playwright install --with-deps
        working-directory: tests
      - name: 'Setup .env file'
        run: cp .env.template .env
      - name: Wait for front to build
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.sha }}
          check-name: 'build-front'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Wait for pusher to build
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.sha }}
          check-name: 'build-pusher'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Wait for back to build
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.sha }}
          check-name: 'build-back'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Wait for chat to build
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.sha }}
          check-name: 'build-chat'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Wait for map-storage to build
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.sha }}
          check-name: 'build-map-storage'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Start WorkAdventure
        run: docker-compose -f docker-compose.yaml -f docker-compose-oidc.yaml -f docker-compose.e2e.yml up -d
        env:
          DOCKER_TAG: ${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
      - name: Wait for environment to Start
        run: sleep 60
      - name: Run Playwright tests
        run: npm run test-prod-like
        working-directory: tests
      - name: Display docker-compose logs on failure
        run: docker-compose -f docker-compose.yaml -f docker-compose-oidc.yaml -f docker-compose.e2e.yml logs
        if: failure()
        env:
          DOCKER_TAG: ${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
      - name: Display containers state
        run: docker-compose -f docker-compose.yaml -f docker-compose-oidc.yaml -f docker-compose.e2e.yml ps
        if: failure()
        env:
          DOCKER_TAG: ${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
      - name: Side-load docker-compose logs in the playwright report
        run: docker-compose -f docker-compose.yaml -f docker-compose-oidc.yaml -f docker-compose.e2e.yml logs > tests/playwright-report/docker-compose.log
        if: failure()
        env:
          DOCKER_TAG: ${{ github.event_name == 'pull_request' && env.GITHUB_HEAD_REF_SLUG || env.GITHUB_REF_SLUG }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 30
