name: Push @workadventure/iframe-api-typings to NPM
on:
  release:
    types: [created]
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Replace version number
        run: 'sed -i "s#VERSION_PLACEHOLDER#${GITHUB_REF/refs\/tags\//}#g" package.json'
        working-directory: "front/packages/iframe-api-typings"

      - name: Debug package.json
        run: cat package.json
        working-directory: "front/packages/iframe-api-typings"

      - name: "Install dependencies"
        run: yarn install
        working-directory: "front"

      - name: "Build"
        run: yarn run build-typings
        env:
          PUSHER_URL: "//localhost:8080"
          ADMIN_URL: "//localhost:80"
        working-directory: "front"

      - name: Install dependencies in package
        run: yarn install
        working-directory: "front/packages/iframe-api-typings"

      - name: Publish package
        run: yarn publish
        working-directory: "front/packages/iframe-api-typings"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ github.event_name == 'release' }}
